### ISSUE TITLE
Update Needs

### ISSUE THREAD

**Issue by jaykukadiya99** [mehdizarepour/text-editor#4]
I request for update this package.
Or can any one suggest how to change dependencies of this package?
I want to change provider version and I need to use in Flutter 2.

**Comment by mehdizarepour** [comment]
Hi @jaykukadiya99, Thank you for opening this issue.
I'm working on it and I will release a new version soon.

**Comment by jaykukadiya99** [comment]
Hi @mehdizarepour,
Thank you for your favourable response.

**Comment by mehdizarepour** [comment]
I've published version `0.4.0`. now you can use it.
